version: '2.1'

services:

  # $ mongo
  mongodb:
    image: mongo:3.6.9
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    healthcheck:
      test: "mongo --eval 'db.stats().ok'"
      interval: 10s
      timeout: 5s
      retries: 10

  # $ mysql -uroot -h127.0.0.1 -p
  mysql:
    image: mysql:5.7
    ports:
     - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 5s
      retries: 10

  # $ rabbitmq
  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

  #zipkin server
  zipkin:
    image: openzipkin/zipkin:2.12.9
    networks:
      - my-network
    environment:
      - STORAGE_TYPE=mem #Could be: mysql
      - RABBIT_ADDRESSES=rabbitmq
      # If using mysql as storage type, provide the following
      #- MYSQL_JDBC_URL=mysql  OR  MYSQL_HOST=mysql
      #- MYSQL_USER={username}
      #- MYSQL_PASS={password}
    ports:
      - 9411:9411
    depends_on:
      rabbitmq:
        condition: service_healthy